import os
import sys
import json
import base64
import mimetypes
from io import BytesIO
import shutil
import subprocess
import datetime
import cv2
import numpy as np
from PIL import Image
import webview
from discovery.scanner import scan_folder, merge_scans
from processing.io_utils import load_gray, load_rgb, save_gray, save_rgb
from processing.roughness import spec_to_roughness
from processing.metalness import spec_to_metallic
from processing.cavity_ao import normal_to_ao
from processing.diffuse_derive import (
    diffuse_to_height,
    height_to_normal,
    height_to_ao,
    diffuse_to_roughness,
    diffuse_to_metal_approx,
)

# Reverse of discovery.name_parser.ROLE_NAMES, for building the JS-side
# populate index: role -> the suffix letter(s) used on disk.
ROLE_TO_SUFFIX = {
    'diffuse': 'D',
    'normal': 'N',
    'metal': 'M',
    'rough': 'R',
    'opacity': 'O',
    'ao': 'AO',
    'spec': 'S',
    'reflection': 'REF',
}
# Inverse lookup, used to guess a role from a generated filename's suffix
# when delivering files that a manifest doesn't explicitly cover.
# 'D' (baseColorMap) is deliberately absent - it's the pre-existing source
# diffuse, never generated by this pipeline, and must never be auto-delivered
# alongside the maps this tool actually produces.
SUFFIX_TO_FIELD = {
    'N': 'normalMap', 'M': 'metallicMap',
    'R': 'roughnessMap', 'AO': 'ambientOcclusionMap', 'O': 'opacityMap',
}

# Cascade rules for generated roles: each role has a "primary" scanned
# source role to prefer, and always falls back to the material's scanned
# diffuse (running the AwesomeBump-style diffuse -> height chain) when the
# primary source isn't available. 'normal' has no primary - a *scanned*
# normal is wired in directly by Populate and is never "generated"; a
# generated normal only ever comes from the diffuse fallback.
GENERATION_ROLE_SOURCES = {
    'rough': {'primary': 'spec'},
    'metal': {'primary': 'spec'},
    'normal': {'primary': None},
    'ao': {'primary': 'normal'},
}
ROLE_SUFFIX = {'rough': 'R', 'metal': 'M', 'normal': 'N', 'ao': 'AO'}

DEFAULT_SETTINGS = {
    # spec-sourced pipeline (unchanged)
    'roughness_gamma': 1.0,
    'metal_low': 0.5,
    'metal_high': 0.85,
    'ao_blur_radius': 3,
    'ao_strength': 1.5,
    # diffuse-sourced fallback pipeline (AwesomeBump-style)
    'diffuse_height_blur': 1,
    'diffuse_height_contrast': 1.0,
    'diffuse_normal_strength': 2.0,
    'diffuse_normal_blur': 0,
    'diffuse_ao_samples': 8,
    'diffuse_ao_radius': 4.0,
    'diffuse_ao_steps': 4,
    'diffuse_ao_strength': 1.0,
    'diffuse_roughness_sensitivity': 1.0,
    'diffuse_roughness_kernel': 5,
    'diffuse_metal_low': 0.5,
    'diffuse_metal_high': 0.85,
}

DEFAULT_USER_PREFERENCES = {
    'accent_color': '#e8974a',
    'light_mode': False,
    'font_scale': 100,
}

TEXCONV_FILENAME = "texconv.exe"

# Default DDS format per delivered stage field. Overridable globally
# (update_dds_defaults) or per exact (material, stage, field) occurrence
# (set_dds_override), since different stages of the same material can
# legitimately want different compression.
DEFAULT_DDS_FORMATS = {
    'baseColorMap': 'BC7_UNORM_SRGB',
    'normalMap': 'BC5_UNORM',
    'metallicMap': 'BC4_UNORM',
    'roughnessMap': 'BC4_UNORM',
    'ambientOcclusionMap': 'BC4_UNORM',
    'opacityMap': 'BC4_UNORM',
    'emissiveMap': 'BC1_UNORM',
}
DEFAULT_MIP_SETTINGS = {'generate_mips': True, 'mip_levels': 0}  # 0 -> texconv's full chain


def get_app_dir():
    """Directory containing the running exe (frozen) or main.py (dev)."""
    if getattr(sys, 'frozen', False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))


APP_DIR = get_app_dir()
WORKING_DIR = os.path.join(APP_DIR, "_working")
os.makedirs(WORKING_DIR, exist_ok=True)
USER_PREFERENCES_PATH = os.path.join(
    APP_DIR, 'settings', 'preferences.json'
)


def project_path_for(materials_path):
    return materials_path + ".pbrproject.json"


class Api:
    def __init__(self):
        self.last_scan = None
        self.texture_folders = self._default_folders()

        self.materials_path = None
        self.materials_data = None

        self.settings = dict(DEFAULT_SETTINGS)
        self.user_preferences = self._load_user_preferences()
        self.delivery_destination = None
        self.level_base_path = None

        self.texconv_path = None
        self.dds_formats = dict(DEFAULT_DDS_FORMATS)
        self.dds_overrides = {}  # "<material>|<stage_index>|<field>" -> DDS format
        self.mip_settings = dict(DEFAULT_MIP_SETTINGS)

        # Single-slot cache for the last diffuse-derived heightmap, so
        # hitting Generate for rough/normal/ao back-to-back on the same
        # stage doesn't recompute the same height field three times.
        self._height_cache = {}

    def _load_user_preferences(self):
        try:
            with open(USER_PREFERENCES_PATH, 'r', encoding='utf-8') as f:
                preferences = json.load(f)
            result = dict(DEFAULT_USER_PREFERENCES)
            result.update(preferences)
            return result
        except (OSError, TypeError, ValueError):
            return dict(DEFAULT_USER_PREFERENCES)

    def get_user_preferences(self):
        return dict(self.user_preferences)

    def update_user_preferences(self, preferences):
        allowed = {'accent_color', 'light_mode'}
        for key, value in (preferences or {}).items():
            if key in allowed:
                self.user_preferences[key] = value
        if 'font_scale' in (preferences or {}):
            try:
                scale = int(preferences['font_scale'])
            except (TypeError, ValueError):
                scale = DEFAULT_USER_PREFERENCES['font_scale']
            if scale in (100, 125, 150):
                self.user_preferences['font_scale'] = scale
        try:
            os.makedirs(os.path.dirname(USER_PREFERENCES_PATH), exist_ok=True)
            with open(USER_PREFERENCES_PATH, 'w', encoding='utf-8') as f:
                json.dump(self.user_preferences, f, indent=2)
        except OSError as e:
            return {'error': f'Could not save user preferences: {e}'}
        return dict(self.user_preferences)

    def _default_folders(self):
        return [{"path": WORKING_DIR, "label": "Working (generated)", "removable": False}]

    # ---- Source: multi-folder texture discovery ----

    def pick_and_add_folder(self):
        """Opens a native folder-picker dialog and adds the result as a scan source."""
        result = webview.windows[0].create_file_dialog(webview.FileDialog.FOLDER)
        if not result:
            return None
        return self.add_texture_folder(result[0])

    def add_texture_folder(self, path, label=None):
        if not any(f["path"] == path for f in self.texture_folders):
            self.texture_folders.append({"path": path, "label": label or path, "removable": True})
        self._save_project()
        return self.rescan_all()

    def remove_texture_folder(self, path):
        self.texture_folders = [f for f in self.texture_folders if not (f["path"] == path and f["removable"])]
        self._save_project()
        return self.rescan_all()

    def list_texture_folders(self):
        return self.texture_folders

    def rescan_all(self):
        """Re-scans every registered folder (including the working dir) and merges the results."""
        scans = [scan_folder(f["path"]) for f in self.texture_folders]
        self.last_scan = merge_scans(scans)
        return self.last_scan

    def get_texture_index(self):
        """
        Flattens the last scan into a lookup the frontend's "populate"/"generate"
        buttons can use directly: {"<token>_<SUFFIX>": "<basename>"}.
        """
        index = {}
        if not self.last_scan:
            return index
        for material_name, info in self.last_scan.get("materials", {}).items():
            for role, full_path in info.get("roles", {}).items():
                suffix = ROLE_TO_SUFFIX.get(role)
                if not suffix:
                    continue
                key = f"{material_name}_{suffix}".lower()
                index[key] = os.path.basename(full_path)
        return index

    # ---- Edit: materials.json load/save ----

    def pick_materials_json(self):
        """Opens a native file-picker dialog for a materials.json file."""
        result = webview.windows[0].create_file_dialog(
            webview.FileDialog.OPEN,
            file_types=('JSON files (*.json)', 'All files (*.*)')
        )
        if not result:
            return None
        return self.load_materials_json(result[0])

    def load_materials_json(self, path):
        try:
            with open(path, 'r', encoding='utf-8') as f:
                data = json.load(f)
        except Exception as e:
            return {"error": f"Could not load materials.json: {e}"}

        self.materials_path = path
        self.materials_data = data

        # Reset to defaults, then overlay a saved project file if one exists
        # alongside this materials.json.
        self.texture_folders = self._default_folders()
        self.settings = dict(DEFAULT_SETTINGS)
        self.delivery_destination = None
        self.level_base_path = None
        self.texconv_path = None
        self.dds_formats = dict(DEFAULT_DDS_FORMATS)
        self.dds_overrides = {}
        self.mip_settings = dict(DEFAULT_MIP_SETTINGS)
        self._height_cache = {}
        self._load_project_if_exists()
        self._add_material_texture_folders()
        self.rescan_all()

        return {
            "path": path,
            "data": data,
            "folders": self.texture_folders,
            "settings": self.settings,
            "delivery_destination": self.delivery_destination,
            "level_base_path": self.level_base_path,
            "dds_settings": self.get_dds_settings(),
        }

    def save_materials_json(self, data):
        """
        Writes a timestamped backup of the file currently on disk, then
        overwrites it with the edited data.
        """
        if not self.materials_path:
            return {"status": "error", "message": "No materials.json is currently loaded."}
        try:
            if os.path.exists(self.materials_path):
                stamp = datetime.datetime.now().strftime('%Y-%m-%d_%H%M%S')
                backup_path = f"{self.materials_path}.{stamp}.bak.json"
                shutil.copy2(self.materials_path, backup_path)
            with open(self.materials_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2)
            self.materials_data = data
        except Exception as e:
            return {"status": "error", "message": f"Save failed: {e}"}
        return {"status": "ok", "message": f"Saved {self.materials_path} (backup written alongside it)"}

    # ---- Project persistence (folders/settings/destination/base path/dds) ----

    def _save_project(self):
        if not self.materials_path:
            return
        proj = {
            "texture_folders": [f for f in self.texture_folders if f.get("removable", True)],
            "settings": self.settings,
            "delivery_destination": self.delivery_destination,
            "level_base_path": self.level_base_path,
            "texconv_path": self.texconv_path,
            "dds_formats": self.dds_formats,
            "dds_overrides": self.dds_overrides,
            "mip_settings": self.mip_settings,
        }
        try:
            with open(project_path_for(self.materials_path), 'w', encoding='utf-8') as f:
                json.dump(proj, f, indent=2)
        except Exception:
            pass  # project persistence is a convenience, not critical path

    def _load_project_if_exists(self):
        p = project_path_for(self.materials_path)
        if not os.path.exists(p):
            return
        try:
            with open(p, 'r', encoding='utf-8') as f:
                proj = json.load(f)
        except Exception:
            return
        for folder in proj.get("texture_folders", []):
            if not any(f["path"] == folder["path"] for f in self.texture_folders):
                self.texture_folders.append(folder)
        self.settings.update(proj.get("settings", {}))
        self.delivery_destination = proj.get("delivery_destination")
        self.level_base_path = proj.get("level_base_path")
        self.texconv_path = proj.get("texconv_path")
        self.dds_formats.update(proj.get("dds_formats", {}))
        self.dds_overrides.update(proj.get("dds_overrides", {}))
        self.mip_settings.update(proj.get("mip_settings", {}))

    def set_level_base_path(self, path):
        self.level_base_path = path
        self._save_project()
        return self.level_base_path

    # ---- Edit: settings ----

    def get_settings(self):
        return self.settings

    def update_settings(self, new_settings):
        self.settings.update(new_settings or {})
        self._height_cache = {}  # any setting change can invalidate the cached height
        self._save_project()
        return self.settings

    # ---- Edit: PBR map generation (cascade: primary scanned source, else diffuse) ----

    def _path_ancestors(self, path):
        current = os.path.abspath(path)
        while True:
            yield current
            parent = os.path.dirname(current)
            if parent == current:
                break
            current = parent

    def _add_material_texture_folders(self):
        """Registers real texture directories resolved from material slots."""
        folders = []
        for material in (self.materials_data or {}).values():
            for stage in material.get('Stages', []):
                if not stage:
                    continue
                for value in stage.values():
                    if not isinstance(value, str) or not value:
                        continue
                    if not value.lower().endswith(('.png', '.jpg', '.jpeg', '.tif', '.tiff', '.dds', '.bmp', '.webp', '.exr')):
                        continue
                    resolved = self._resolve_slot_path(value)
                    if resolved and os.path.isfile(resolved):
                        folder = os.path.dirname(resolved)
                        if folder not in folders:
                            folders.append(folder)
        for folder in folders:
            if not any(item['path'] == folder for item in self.texture_folders):
                self.texture_folders.append({'path': folder, 'label': folder, 'removable': True})
        if folders:
            self._save_project()

    def _find_material_data(self, material_name):
        for name, material in (self.materials_data or {}).items():
            if name.lower() == material_name.lower():
                return material
        return None

    def _resolve_slot_path(self, value):
        if not isinstance(value, str) or not value:
            return None
        path = os.path.normpath(value.replace('/', os.sep))
        is_virtual_path = value.startswith('/') or value.startswith('\\')
        if os.path.isabs(path) and not is_virtual_path:
            return path
        candidates = []
        if self.level_base_path:
            candidates.append(os.path.join(self.level_base_path, path))
        if self.materials_path:
            candidates.append(os.path.join(os.path.dirname(self.materials_path), path))
        candidates.append(os.path.join(APP_DIR, path))
        if is_virtual_path:
            virtual_path = path.lstrip('/\\')
            for ancestor in self._path_ancestors(os.path.dirname(self.materials_path or APP_DIR)):
                candidates.append(os.path.join(ancestor, virtual_path))
        for candidate in candidates:
            if os.path.isfile(candidate):
                return candidate
        # materials.json may contain game-relative paths such as
        # /levels/<level>/Assets/Textures/file.dds. The registered texture
        # folders are the filesystem roots that own those assets, so match
        # the assigned filename there when the virtual prefix is unavailable.
        filename = os.path.basename(path)
        for folder in self.texture_folders:
            root = folder.get('path')
            if not root or not os.path.isdir(root):
                continue
            for current_root, _, filenames in os.walk(root):
                for current_name in filenames:
                    if current_name.lower() == filename.lower():
                        return os.path.join(current_root, current_name)
        return candidates[0] if candidates else path

    def _slot_diffuse_path(self, material_name, stage_index):
        material = self._find_material_data(material_name)
        stages = material.get('Stages', []) if material else []
        try:
            stage = stages[int(stage_index)]
        except (IndexError, TypeError, ValueError):
            return None
        path = self._resolve_slot_path(stage.get('baseColorMap')) if stage else None
        return path if path and os.path.isfile(path) else None

    def _load_reflection_mask(self, material, shape_hw):
        """
        Loads the material's scanned _REF mask (if any) and resizes it to
        match `shape_hw` (H, W). _REF marks flat reflective surfaces
        (glass, mirrors, etc.) as non-black; everything generation-wise
        that cares about "is this pixel glass" - normal, roughness, metal -
        shares this one lookup instead of re-reading/resizing the file
        three times.

        Returns (mask, reflection_gray) where mask is a boolean array and
        reflection_gray is the (resized) float [0,1] mask itself, or
        (None, None) if there's no usable _REF scanned for this material.
        """
        reflection_path = material.get("roles", {}).get("reflection")
        if not reflection_path or not os.path.isfile(reflection_path):
            return None, None
        try:
            reflection_gray = load_gray(reflection_path)
            if reflection_gray.shape[:2] != shape_hw:
                reflection_gray = cv2.resize(
                    reflection_gray, (shape_hw[1], shape_hw[0]), interpolation=cv2.INTER_LINEAR
                )
            mask = reflection_gray > 0.01
            return mask, reflection_gray
        except Exception:
            return None, None

    def _resolve_generation_source(self, material, role, material_name=None, stage_index=0):
        """Returns the role name to actually source `role` from ('spec',
        'normal', or 'diffuse'), or None if nothing usable is scanned."""
        rule = GENERATION_ROLE_SOURCES[role]
        primary_role = rule.get('primary')
        roles = material.get('roles', {})
        if primary_role and roles.get(primary_role):
            return primary_role
        if roles.get('diffuse'):
            return 'diffuse'
        if material_name and self._slot_diffuse_path(material_name, stage_index):
            return 'diffuse-slot'
        return None

    def get_generation_status(self, material_name, stage_index=0):
        """
        Per-role status for the PBR generator panel: which source each
        generatable role would actually use right now, so the UI can show
        e.g. "metal - using: spec" vs "metal - using: diffuse (approx.)"
        without duplicating the cascade logic in JS.
        """
        material = (self.last_scan or {}).get('materials', {}).get(material_name, {'roles': {}})
        status = {}
        for role in GENERATION_ROLE_SOURCES:
            source = self._resolve_generation_source(material, role, material_name, stage_index)
            status[role] = {"source": source, "approximate": source in ('diffuse', 'diffuse-slot')}
        return status

    def get_preview_image(self, material_name, role, stage_index=0):
        """Returns a scanned/generated texture as a data URL for the webview previews."""
        material = (self.last_scan or {}).get('materials', {}).get(material_name)
        path = material.get('roles', {}).get(role) if material else None
        if not path and role == 'diffuse':
            path = self._slot_diffuse_path(material_name, stage_index)
        if not path or not os.path.isfile(path):
            return {'error': f'No readable {role} texture was resolved'}
        try:
            if path.lower().endswith('.dds'):
                rgb = load_rgb(path)
                image = Image.fromarray(np.clip(rgb * 255.0, 0, 255).astype(np.uint8), 'RGB')
                buffer = BytesIO()
                image.save(buffer, format='PNG')
                image_bytes = buffer.getvalue()
                mime = 'image/png'
            else:
                with open(path, 'rb') as image_file:
                    image_bytes = image_file.read()
                mime = mimetypes.guess_type(path)[0] or 'image/png'
            encoded = base64.b64encode(image_bytes).decode('ascii')
        except OSError as error:
            return {'error': f'Could not read {os.path.basename(path)}: {error}'}
        except Exception as error:
            return {'error': f'Could not decode {os.path.basename(path)}: {error}'}
        return {
            'data_url': f'data:{mime};base64,{encoded}',
            'filename': os.path.basename(path),
            'source_path': path,
            'role': role,
        }

    def _get_height_for_diffuse(self, diffuse_path):
        """Computes (or returns the cached) AwesomeBump-style heightfield
        for a diffuse image, keyed on its path/mtime/settings so repeated
        Generate clicks on the same stage don't redo this each time."""
        blur = int(self.settings.get('diffuse_height_blur', 1))
        contrast = float(self.settings.get('diffuse_height_contrast', 1.0))
        try:
            mtime = os.path.getmtime(diffuse_path)
        except OSError:
            mtime = None
        key = (diffuse_path, mtime, blur, contrast)

        cached = self._height_cache.get(key)
        if cached is not None:
            return cached

        diffuse_rgb = load_rgb(diffuse_path)
        height = diffuse_to_height(diffuse_rgb, blur_radius=blur, contrast=contrast)
        self._height_cache = {key: height}  # single slot is enough for one Generate session
        return height

    def generate_map(self, material_name, role, stage_index=0):
        """
        Generates a metal/rough/normal/ao map for material_name, sourcing
        from its scanned spec/normal file when available, and otherwise
        falling back to an AwesomeBump-style derivation from the scanned
        diffuse (height -> normal/ao, contrast -> roughness, luminance
        heuristic -> metal approximation).

        Writes into the working directory (next to the app, NOT next to
        the source file) - it stays there until Deliver converts+copies it
        to its real destination, and is only removed by the working-folder
        cleanup on app close or a manual "Clear working folder".
        """
        if role not in GENERATION_ROLE_SOURCES:
            return {"status": "error", "message": f"No generation rule for role '{role}'."}

        material = (self.last_scan or {}).get("materials", {}).get(material_name, {"roles": {}, "missing": []})

        source_role = self._resolve_generation_source(material, role, material_name, stage_index)
        if not source_role:
            primary = GENERATION_ROLE_SOURCES[role].get('primary')
            hint = f"{primary} or diffuse" if primary else "diffuse"
            return {
                "status": "error",
                "message": f"'{material_name}' has no {hint} map to generate {role} from.",
            }

        source_path = self._slot_diffuse_path(material_name, stage_index) if source_role == 'diffuse-slot' else material["roles"][source_role]
        # Generated intermediates must use a codec OpenCV can write. DDS is
        # an input/delivery format here; texconv handles the final DDS file.
        ext = '.png'
        out_name = f"0x00000000_{material_name}_{ROLE_SUFFIX[role]}{ext}"
        out_path = os.path.join(WORKING_DIR, out_name)

        settings = self.settings
        try:
            if role == 'rough':
                if source_role == 'spec':
                    result = spec_to_roughness(load_gray(source_path), gamma=settings['roughness_gamma'])
                else:
                    height = self._get_height_for_diffuse(source_path)
                    kernel_size = max(1, int(settings['diffuse_roughness_kernel']))
                    result = diffuse_to_roughness(
                        height,
                        sensitivity=settings['diffuse_roughness_sensitivity'],
                        kernel_size=kernel_size,
                    )
                # Workaround: the metalness mask logic works; mirror it and
                # invert so roughness is the exact inverse of metalness.
                mask, _reflection_gray = self._load_reflection_mask(material, result.shape[:2])
                if mask is not None:
                    if source_role == 'spec':
                        metal = spec_to_metallic(load_gray(source_path), low=settings['metal_low'], high=settings['metal_high'])
                    else:
                        metal = diffuse_to_metal_approx(
                            load_rgb(source_path),
                            low=settings['diffuse_metal_low'],
                            high=settings['diffuse_metal_high'],
                        )
                    metal = np.where(mask, 1.0, 0.0).astype(metal.dtype)
                    result = (1.0 - metal).astype(result.dtype)
                save_gray(out_path, result)

            elif role == 'metal':
                if source_role == 'spec':
                    result = spec_to_metallic(load_gray(source_path), low=settings['metal_low'], high=settings['metal_high'])
                else:
                    result = diffuse_to_metal_approx(
                        load_rgb(source_path),
                        low=settings['diffuse_metal_low'],
                        high=settings['diffuse_metal_high'],
                    )
                # Same reasoning inverted: glass reads fully metallic (1.0),
                # everything else reads non-metallic (0.0) - again replacing
                # the whole map, not blending with the computed value.
                mask, _reflection_gray = self._load_reflection_mask(material, result.shape[:2])
                if mask is not None:
                    result = np.where(mask, 1.0, 0.0).astype(result.dtype)
                save_gray(out_path, result)

            elif role == 'normal':
                # Only ever reached via the diffuse fallback - a scanned
                # normal is wired in by Populate and is never "generated".
                height = self._get_height_for_diffuse(source_path)
                normal_rgb = height_to_normal(
                    height,
                    strength=settings['diffuse_normal_strength'],
                    blur_radius=int(settings['diffuse_normal_blur']),
                )

                # Apply reflection mask: reflective areas (non-black in _REF)
                # get the neutral tangent-space normal (0.5, 0.5, 1.0).
                mask, _reflection_gray = self._load_reflection_mask(material, normal_rgb.shape[:2])
                if mask is not None:
                    normal_rgb[mask] = [0.5, 0.5, 1.0]

                save_rgb(out_path, normal_rgb)

            elif role == 'ao':
                if source_role == 'normal':
                    result = normal_to_ao(
                        load_rgb(source_path),
                        blur_radius=settings['ao_blur_radius'],
                        strength=settings['ao_strength'],
                    )
                else:
                    height = self._get_height_for_diffuse(source_path)
                    result = height_to_ao(
                        height,
                        samples=int(settings['diffuse_ao_samples']),
                        radius=settings['diffuse_ao_radius'],
                        steps=int(settings['diffuse_ao_steps']),
                        strength=settings['diffuse_ao_strength'],
                    )
                save_gray(out_path, result)

            else:
                return {"status": "error", "message": f"Unhandled role '{role}'."}

        except Exception as e:
            return {"status": "error", "message": f"Generation failed: {e}"}

        # Keep the in-memory scan in sync so the Source table reflects the new
        # file without requiring a manual rescan.
        if self.last_scan is None:
            self.last_scan = {"materials": {}, "unmatched": []}
        scan_material = self.last_scan.setdefault("materials", {}).setdefault(
            material_name, {"roles": {}, "missing": []}
        )
        scan_material["roles"][role] = out_path
        material = scan_material
        if role in material.get("missing", []):
            material["missing"].remove(role)

        approx_note = " (approximated from diffuse)" if source_role in ('diffuse', 'diffuse-slot') else ""
        return {
            "status": "ok",
            "message": f"Generated {role} for '{material_name}' from {source_role}{approx_note} -> {out_name}",
            "filename": out_name,
            "source": source_role,
            "approximate": source_role in ('diffuse', 'diffuse-slot'),
        }

    # ---- Deliver: destination + texconv/DDS settings ----

    def pick_delivery_destination(self):
        result = webview.windows[0].create_file_dialog(webview.FileDialog.FOLDER)
        if not result:
            return None
        self.delivery_destination = result[0]
        self._save_project()
        return self.delivery_destination

    def _default_texconv_path(self):
        return os.path.join(APP_DIR, TEXCONV_FILENAME)

    def _resolve_texconv_path(self):
        if self.texconv_path and os.path.isfile(self.texconv_path):
            return self.texconv_path
        default = self._default_texconv_path()
        if os.path.isfile(default):
            return default
        return None

    def pick_texconv_path(self):
        result = webview.windows[0].create_file_dialog(
            webview.FileDialog.OPEN, file_types=('Executable (*.exe)', 'All files (*.*)')
        )
        if not result:
            return None
        self.texconv_path = result[0]
        self._save_project()
        return self.get_dds_settings()

    def check_texconv(self):
        path = self._resolve_texconv_path()
        if not path:
            return {
                "status": "error",
                "message": f"texconv.exe not found in the app folder ({self._default_texconv_path()}) "
                           f"or at the configured path.",
            }
        try:
            subprocess.run([path, '-help'], capture_output=True, timeout=5)
            return {"status": "ok", "message": f"texconv found: {path}"}
        except Exception as e:
            return {"status": "error", "message": f"Found {path} but couldn't run it: {e}"}

    def get_dds_settings(self):
        return {
            "texconv_path": self.texconv_path,
            "texconv_resolved": self._resolve_texconv_path(),
            "default_texconv_path": self._default_texconv_path(),
            "formats": dict(self.dds_formats),
            "overrides": dict(self.dds_overrides),
            "mip_settings": dict(self.mip_settings),
        }

    def update_dds_defaults(self, formats):
        self.dds_formats.update(formats or {})
        self._save_project()
        return self.get_dds_settings()

    def update_mip_settings(self, mip_settings):
        self.mip_settings.update(mip_settings or {})
        self._save_project()
        return self.get_dds_settings()

    def set_dds_override(self, material_name, stage_index, field, dds_format):
        """dds_format=None/'' clears the override, falling back to the
        global per-field default for this (material, stage, field)."""
        key = f"{material_name}|{stage_index}|{field}"
        if dds_format:
            self.dds_overrides[key] = dds_format
        else:
            self.dds_overrides.pop(key, None)
        self._save_project()
        return self.get_dds_settings()

    # ---- Deliver: working-folder stats + manual cleanup ----

    def get_working_folder_stats(self):
        count = 0
        total_bytes = 0
        for fname in os.listdir(WORKING_DIR):
            fpath = os.path.join(WORKING_DIR, fname)
            if os.path.isfile(fpath):
                count += 1
                try:
                    total_bytes += os.path.getsize(fpath)
                except OSError:
                    pass
        return {"file_count": count, "total_bytes": total_bytes}

    def list_working_folder_files(self):
        """
        Plain filename listing of everything currently in the working
        folder. The frontend uses this to build the delivery manifest -
        matching each stage field's basename against what's actually on
        disk (rather than assuming the field's extension matches the
        working file's editable extension).
        """
        return sorted(
            f for f in os.listdir(WORKING_DIR) if os.path.isfile(os.path.join(WORKING_DIR, f))
        )

    def clear_working_folder(self):
        """
        Manual purge, since Deliver no longer deletes working-folder files
        automatically (kept for re-delivery/inspection until app close).
        """
        removed = 0
        for fname in os.listdir(WORKING_DIR):
            fpath = os.path.join(WORKING_DIR, fname)
            if os.path.isfile(fpath):
                try:
                    os.remove(fpath)
                    removed += 1
                except OSError:
                    pass
        self._height_cache = {}
        self.rescan_all()
        return {"status": "ok", "message": f"Cleared {removed} file(s) from the working folder.", "removed": removed}

    # ---- Deliver: texconv-backed, non-destructive ----

    def _run_texconv(self, src_path, dst_dir, dds_format):
        texconv = self._resolve_texconv_path()
        if not texconv:
            raise RuntimeError(
                f"texconv.exe not found (checked {self._default_texconv_path()} and the configured path)"
            )
        args = [texconv, '-f', dds_format, '-o', dst_dir, '-y']
        if not self.mip_settings.get('generate_mips', True):
            args += ['-m', '1']
        elif self.mip_settings.get('mip_levels'):
            args += ['-m', str(self.mip_settings['mip_levels'])]
        args.append(src_path)
        proc = subprocess.run(args, capture_output=True, text=True, timeout=180)
        if proc.returncode != 0:
            raise RuntimeError(proc.stderr.strip() or proc.stdout.strip() or f"texconv exited {proc.returncode}")

    def deliver_generated(self, manifest=None):
        """
        Converts every file currently sitting in the working directory to
        DDS via texconv and copies the result to the delivery destination.
        Working-folder originals are LEFT IN PLACE - nothing is deleted
        here; that only happens via clear_working_folder() or the
        app-close cleanup in main.py.

        manifest: optional list of
            {"source": "<filename in _working>", "format": "<DDS format>", "output_name": "<name.dds>"}
        Lets the caller (frontend, which knows per-stage-field format
        overrides) control exactly which format each file converts to, and
        rename outputs when the same working file must be delivered under
        more than one format for different stage fields. Any working file
        not covered by the manifest is delivered using its role's default
        format (guessed from its filename suffix), named <basename>.dds.
        """
        if not self.delivery_destination:
            return {"status": "error", "message": "Choose a delivery destination first."}

        texconv = self._resolve_texconv_path()
        if not texconv:
            return {
                "status": "error",
                "message": f"texconv.exe not found (checked {self._default_texconv_path()} and the "
                           f"configured path). Set it on the Deliver tab.",
            }

        os.makedirs(self.delivery_destination, exist_ok=True)

        manifest_by_source = {}
        for entry in (manifest or []):
            manifest_by_source.setdefault(entry["source"], []).append(entry)

        working_files = [
            f for f in os.listdir(WORKING_DIR) if os.path.isfile(os.path.join(WORKING_DIR, f))
        ]

        jobs = []  # (source_filename, output_name, dds_format)
        skipped = []
        for fname in working_files:
            entries = manifest_by_source.get(fname)
            if entries:
                for entry in entries:
                    jobs.append((
                        fname,
                        entry.get("output_name") or os.path.splitext(fname)[0] + ".dds",
                        entry.get("format") or "BC1_UNORM",
                    ))
            else:
                suffix_guess = fname.rsplit('_', 1)[-1].split('.')[0]
                field_guess = SUFFIX_TO_FIELD.get(suffix_guess)
                if field_guess is None:
                    # baseColorMap ("_D") and any other unrecognized suffix
                    # are never auto-delivered - baseColor already exists
                    # as a proper source DDS and isn't something this
                    # pipeline generates or converts.
                    skipped.append(fname)
                    continue
                fmt = self.dds_formats.get(field_guess, 'BC1_UNORM')
                jobs.append((fname, os.path.splitext(fname)[0] + ".dds", fmt))

        delivered, failed = [], []
        for fname, out_name, fmt in jobs:
            src_path = os.path.join(WORKING_DIR, fname)
            try:
                self._run_texconv(src_path, self.delivery_destination, fmt)
                produced = os.path.join(self.delivery_destination, os.path.splitext(fname)[0] + ".dds")
                final_path = os.path.join(self.delivery_destination, out_name)
                if produced != final_path:
                    if os.path.exists(final_path):
                        os.remove(final_path)
                    os.replace(produced, final_path)
                delivered.append(out_name)
            except Exception as e:
                failed.append({"file": fname, "error": str(e)})

        if not delivered and not failed:
            message = "Nothing in the working folder to deliver."
            if skipped:
                message += f" ({len(skipped)} file(s) skipped: {', '.join(skipped)})"
            return {"status": "ok", "message": message, "delivered": [], "failed": [], "skipped": skipped}

        status = "ok" if not failed else ("error" if not delivered else "partial")
        message = f"Delivered {len(delivered)} file(s) to {self.delivery_destination}"
        if skipped:
            message += f", {len(skipped)} skipped"
        if failed:
            message += f", {len(failed)} failed"
        return {"status": status, "message": message, "delivered": delivered, "failed": failed, "skipped": skipped}
